doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Document:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Document/Infra/ORM/Doctrine/Mapping'
                prefix: 'App\Document\Domain\Model'
                alias: Document
